FROM jenkins/jenkins:2.330
USER root
RUN apt-get update && apt-get install -y make git openjdk-8-jdk
RUN mkdir /opt/backup && chown jenkins:jenkins /opt/backup
USER jenkins
RUN echo 2.330 > /usr/share/jenkins/ref/jenkins.install.UpgradeWizard.state
RUN echo 2.330 > /usr/share/jenkins/ref/jenkins.install.InstallUtil.lastExecVersion
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
COPY --chown=jenkins:jenkins config_jenkins /var/jenkins_home                ----> Pasta do backup config_jenkins  (backup é realizado no volume local /opt/backup
                                                                                   para recover criar uma pasta config_jenkins e extrair o conteudo do backup no mesmo
                                                                                   path do dockerfile.
